---
title: "soil pH"
author: "Greg McKittrick"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages
library(ggplot2)
library(tidyverse)
library(readxl)
library(dplyr)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
```

## Create Output directory

```{r}

# Get current date
current_date <- Sys.Date()

# Format date as yyyy-mm-dd
date_string <- format(current_date, "%Y-%m-%d")

# Create output folder path
output_folder <- paste0("../Output/", date_string, "/")

# Create output folder if it doesn't exist
if (!file.exists(output_folder)) {
  dir.create(output_folder, recursive = TRUE)
}

# Now you can use the output_folder variable to save your output
# For example:
# saveRDS(your_output_data, file = paste0(output_folder, "output_data.rds"))
```



## load in data
```{r}
pHData <- read_excel("../Fucose post-Incubation soil pH.xlsx", sheet = 2)

# Convert variables to appropriate types
pHData$Treatment <- as.factor(pHData$Treatment)

```

## Perform One-way ANOVA analysis on pH data

```{r}

#Reorder the Treatments so that Soil Only is first
pHData <- pHData %>%
mutate(Treatment = fct_relevel(Treatment, "Soil Only")) 
str(pHData)

#One way anova using lm
OneWayFit <- lm(pH ~ Treatment, data = pHData)

#Compare all the treatments to control (Soil Only)
emmeans_results <- emmeans(OneWayFit, dunnett ~ Treatment)

emmeans_results

# Capture the output of emmeans()
emmeans_output <- capture.output(summary(emmeans_results))

# Write the captured output to a text file
writeLines(emmeans_output, con = paste0(output_folder, "pH_aov_emmeans.txt"))
```

##Create a Summary of pHData

```{r}
# Create a summary of the cumulative CO2 C data 
summarypHData <- pHData %>%
  group_by(Treatment) %>%
  summarise(n = n(),
    avg_pH = mean(pH),
            stdDev = sd(pH))
```

##Create a summary box plot of SIR

```{r}
p <- ggplot(pHData, aes(x = Treatment, y = pH,fill = Treatment))+
  geom_boxplot()+
  labs(title = "Summary Post Incubation pH",
       x = "Treatment",
       y = "pH") +
  theme_minimal() +
  theme(axis.text.x = element_blank())+
  theme(
    plot.title = element_text(size = 20),     # Title font size
    axis.title.x = element_text(size = 15),   # X axis label font size
    axis.title.y = element_text(size = 15)    # Y axis label font size
  )

  
p

#Save the plot in output folder
ggsave( file = paste0 (output_folder, "summary_pH.pdf"), p)
```

